### ISSUE TITLE
Checklist for v0.20.0

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#221]
- [x] Register `starfederation/datastar` in jsdelivr and update installation instructions in README and the docs.
- [x] Rename the `starfederation/datastar` repo to `datastar-0.20.0` and make it private.
- [x] Transfer the `delaneyj/datastar` repo.
- [x] Assign contributors to transfered repo.
- [x] Ensure `Allow merge commits` is disabled under `Pull Requests` in repo settings.
- [x] Transfer open issues over from private to public repo.
