### ISSUE TITLE
 Checklist for v0.21.0

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#265]
- [ ] Remove the `$` prefix for actions.
- [ ] Rename `data-store` to `data-merge-signals`.
- [ ] Rename `store` to `signals` in all SDKs.
- [ ] Rename `data-model` to `data-bind`.
- [ ] Add error message in console when a `$` prefix is used where it shouldn’t be, for example `data-bind="$mysignal"`.
- [ ] Fix newline in SDK protocol for `paths`.

**Comment by delaneyj** [comment]
i broken into milestone issues, easier to track that way imo
